### ISSUE TITLE
Adding a wildcard record

### ISSUE THREAD

**Issue by skunkie** [bodgit/tsig#45]
Is it possible to add a wildcard record?
 If I try to add "*.example.com. 300 A 192.0.2.1", I get this error:
`
"unexpected acceptor flag is not set: expecting a token from the acceptor, not in the initiator"
`

**Comment by bodgit** [comment]
Windows doesn't seem to allow creating wildcard DNS records using dynamic updates. I can't get it to work if I use `nsupdate` as an alternative.

**Comment by bodgit** [comment]
I've updated the README. There's possibly other limitations that Windows DNS servers have which I haven't discovered yet.
